### PR TITLE
counting sort algorithm

### PR DESCRIPTION
**Pull request by chirayujain98**
It works by counting the number of objects having distinct key values (something like hashing). Then doing some arithmetic to calculate the position of each object in the output sequence.

### CODE REVIEW

**Comment by manojsrivatsavsfu** [comment]
Why is this code in .txt format ?
is this some kind of way to bypass the codacy PR review?

**Comment by prateekiiest** [comment]
@manojkun , I didnt notice that. Thanks for letting me know
@chirayujain98 please send a new PR in a cpp file extension not .txt.

**Comment by prateekiiest** [comment]
maybe codacy/ codeclimate bypassed that

**Comment by chirayujain98** [comment]
OK....I'll send it

**Pull request merged**
