### PR TITLE
add python implementation of some of the given algorithm

### PR DESCRIPTION
**Pull request by ashubly25**
## ISSUE NUMBER  #263  
https://github.com/codeIIEST/Algorithms/issues/263

### CODE REVIEW

**Comment by prateekiiest** [comment]
test fails

**Comment by ashubly25** [comment]
Can I do anything I know it's 1 Jan!

**Comment by prateekiiest** [comment]
you can contribute further but KWOC officially ends today if you go by their timeline

**Comment by ashubly25** [comment]
Should my contribution count to what I did till now? I would love contribute further.

**Comment by ashubly25** [comment]
Will I am going to get certificate?

**Comment by srachet** [comment]
#263

**Pull request closed without merging**
