### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by nitishtw**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
Why all those commits are showing up ?

**Comment by prateekiiest** [comment]
create a branch first for each PR

**Comment by nitishtw** [comment]
i don't know how to create a branch for each commit ?

**Comment by prateekiiest** [comment]
@soubh1k please help him

**Comment by soubh1k** [comment]
Goto your local repo

On the left, there's a option to select branches. Click it and create a new branch. Make your changes in the new branch. Then create pull request from the new branch.

**Comment by soubh1k** [comment]
Sorry, I had closed it by mistake.

**Review by soubh1k — COMMENTED** [review]
Its alright. Just do what is said above.

**Comment by soubh1k** [comment]
If no one is doing this, then lets assign someone else.

**Comment by prateekiiest** [comment]
I am closing this as this PR construct is not good.
Please follow the above rules and create a new PR

**Pull request closed without merging**
