### PR TITLE
Stack and Queue added to new folder Data Structures

### PR DESCRIPTION
**Pull request by Arkadyuti30**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.
Added a new folder in the folder "Competitive Coding" called "Data Structures" and added "Stack" and "Queue" to it.

## TESTING

Please provide the necessary steps to test the solution.
Implementation of Stack and Queue in Java. Can be run on the terminal or any IDE.

### CODE REVIEW

**Comment by prateekiiest** [comment]
please fix the issues

**Comment by prateekiiest** [comment]
lemme know if you are facing problem @Arkadyuti30

**Comment by Arkadyuti30** [comment]
Hi, I am not being able to understand how to fix the issues. Like I can see
the issues but how do I edit my file?
Thanks.

**Comment by prateekiiest** [comment]
you can see a pen icon to the right in your commit

**Comment by Arkadyuti30** [comment]
Thank you so much, I have found out how to edit. I fixed some issues. There
are a few more. I will work on them later. I have an exam tomorrow. I am
really sorry for this inconvenience.

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
