### PR TITLE
Heapsort

### PR DESCRIPTION
**Pull request by abcdjdj**
Implement Heap Sort in C and update the README

### CODE REVIEW

**Review by prateekiiest — CHANGES_REQUESTED** [review]
Please make a new folder called Heapsort and under that include the code and readme

**Comment by abcdjdj** [comment]
Hope it's all okay now. Sorry for the delay

**Comment by soubh1k** [comment]
Sorry for being late, but please include a test case inside the program. In other words, **avoid taking input from the user**. You may consider an array of a fixed size yourself.

Call heapsort from main function.

**Comment by abcdjdj** [comment]
@soubh1k Done

**Comment by soubh1k** [comment]
I am closing this pull request. Fork the new repo with the new directory structure. Insert the file in the Algorithms/Competitive Coding/sorting/heapsort folder along with the readme. Then create a new Pull Request.

The code is alright.

**Pull request closed without merging**
