### PR TITLE
Chinese Remainder Theorem in cpp

### PR DESCRIPTION
**Pull request by Priyangshuyogi**
## ISSUE NUMBER

#185 

## SHORT DESCRIPTION

Description of Chinese Remainder Theorem with cpp code and also describing the Modular Multiplicative Inverse theorem which is implemented in the Code for CRT with description and cpp code in separate folders.

##LOCATION 
I am adding this in the math folder of Competitive Programming.

### CODE REVIEW

**Comment by Priyangshuyogi** [comment]
sir please go through this and tell me if any improvement is needed.

**Comment by rahulkumaran** [comment]
@prateekiiest , the codes work fine! Also comments are written wherever necessary with good readme documentations too

**Comment by Priyangshuyogi** [comment]
Thank you for your response.

**Comment by Priyangshuyogi** [comment]
@prateekiiest please see it.

**Review by prateekiiest — APPROVED** [review]

**Comment by prateekiiest** [comment]
Looks good 🎆 

Thanks for the contribution :1st_place_medal:

**Pull request merged**
