### PR TITLE
LuckyNumber

### PR DESCRIPTION
**Pull request by Priyangshuyogi**
Thank you for your contribution. Please provide the details requested below.

## 185

link to the issue this pull request addresses  https://github.com/codeIIEST/Algorithms/issues/185

## SHORT DESCRIPTION

i have added a new folder named LuckyNumber to the math folder in Competitive Coding.

### CODE REVIEW

**Comment by prateekiiest** [comment]
can you please elaborate what you are working on @Priyangshuyogi ?

**Comment by Priyangshuyogi** [comment]
I am writing on some math based Algorithms which are often used in Competitive programming.

**Comment by Priyangshuyogi** [comment]
I am writing theses Algorithms in the math folder under competitive programming section.

**Review by prateekiiest — CHANGES_REQUESTED** [review]
Good work!

Just some changes.

It should be a README.md file not that extension that you gave 😃

**Comment by Priyangshuyogi** [comment]
Thank you 😃. I am fixing it.

**Comment by Priyangshuyogi** [comment]
okay sir. I have fixed it. Please merge it.

**Review by prateekiiest — APPROVED** [review]
Looks Good 🎆

**Pull request merged**
