### PR TITLE
Added greedy algorithms

### PR DESCRIPTION
**Pull request by abhisheknalla**
ISSUE NUMBER 
#236

SHORT DESCRIPTION
Sir, I added 5 greedy algorithms. I added commented code along with input prompts and readme files. 

TESTING
 The test cases are in the readme files. Sir, please review
--

### CODE REVIEW

**Comment by abhisheknalla** [comment]
Sir, can you review this PR

**Comment by abhisheknalla** [comment]
sir, please review this PR

**Comment by prateekiiest** [comment]
Please specify which greedy algorithm you are working on ?

**Comment by abhisheknalla** [comment]
activitySelection
jobSequencing   
KruskalMst  
PrimMst

**Comment by prateekiiest** [comment]
already kruskal , prims implemented under Tress

**Comment by m1h1mm** [comment]
Hi

**Comment by prateekiiest** [comment]
I am closing this. Since its the same thing being added.
Reopen if any updates

**Pull request closed without merging**
