### PR TITLE
Project Euler problem 21 - sum of Amicable numbers upto 10000

### PR DESCRIPTION
**Pull request by Arkadyuti30**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.

This is the program for problem 21 on Project Euler to find the sum of Amicable numbers till 10000.

## TESTING

Please provide the necessary steps to test the solution.

The output of the program gives the solution.

### CODE REVIEW

**Comment by Arkadyuti30** [comment]
Please accept my pull request.

**Comment by Arkadyuti30** [comment]
Fixed all issues. Please accept my pull request.

**Review by prateekiiest — CHANGES_REQUESTED** [review]
why multiple files?

and where's the readme ?

**Comment by Arkadyuti30** [comment]
There is one **.java** file and one **.class** file. Should I remove the .class file?

I am so sorry. Adding the readme.

**Comment by prateekiiest** [comment]
make all the files under one folder only

**Pull request closed without merging**
