### PR TITLE
Update SortsTutorial.md

### PR DESCRIPTION
**Pull request by prateekiiest**

### CODE REVIEW

**Comment by smitbose** [comment]
@prateekiiest I don't think you are quite understanding the layout of Jekyll. Have you taken a look at the wiki? Just tell me how are you testing the code in your local machine? Do you have jekyll installed?

**Comment by prateekiiest** [comment]
@smitbose   I don't have jekyll installed.

**Comment by prateekiiest** [comment]
under the gh-pages  branch I have uploaded some the tutorials

**Comment by smitbose** [comment]
Install jekyll, test it on your local machine. See if its rendering properly, and then push. Jekyll uses some meta kinda stuff on each blog, that is required for the rendering of the pages. Just look at the project wiki page of this repository, you'll get an idea of the manner in which you should write those metas. Let me know in case you face problem. 
I don't know whether you are getting this correctly or not but the task of contributing here is not merely displaying the .md's on Github, but to make them render on this [website](https://codeiiest.github.io/Algorithms).

**Comment by prateekiiest** [comment]
ok, i didn't get it. Sorry. 
I am installing jekyll.

**Pull request closed without merging**
