### PR TITLE
Gnome sort algorithm

### PR DESCRIPTION
**Pull request by chirayujain98**
Gnome sort is a sorting algorithm which is similar to Insertion sort, except that moving an element to its proper place is accomplished by a series of swaps, as in Bubble Sort.

### CODE REVIEW

**Comment by abiduzz420** [comment]
@chirayujain98 Give appropriate pull request title in accordance to commits made. You have also added radix sort algorithm and recursive bubble sort algorithm in the PR. Since you have already made PRs for Recursive bubble sort and Radix sort algorithm, could you remove these files from this particular PR ?

**Comment by chirayujain98** [comment]
@abiduzz420 actually I just started to contribute on Github and I didn't knew that the PR i made would include the recursive and radix too. Surely I will do the changes. Thanks :)

**Comment by chirayujain98** [comment]
Please could you tell me how can I do that?

**Comment by soubh1k** [comment]
I am closing this pull request. The current directory structure has been changed. Fork the new repo with the new directory structure. Insert the files in the new directory structure along with the appropriate readme's. Then create a new Pull Request.

After you get the latest repo, only add the files in the respective folders. Then create a new PR.

**Pull request closed without merging**
