### PR TITLE
Added Manacher's algorithm in python

### PR DESCRIPTION
**Pull request by dhruvapte26**
Given a string, find the longest substring which is a palindrome- a typical competitive programming question :wink:

### CODE REVIEW

**Comment by prateekiiest** [comment]
is it somewhat related to topological sort @the-ethan-hunt ?

**Comment by prateekiiest** [comment]
also your fork isnt updated

**Comment by prateekiiest** [comment]
now create a new PR from this updated repo

**Comment by dhruvapte26** [comment]
Alright

**Pull request closed without merging**
