### PR TITLE
Code for Caesarcipher in Python

### PR DESCRIPTION
**Pull request by rahulkumaran**
This is a code for Caesarcipher in Python.
You can test the following code by compiling it and then giving a string and a key value and accordingly the encryption and decryption will take place.

### CODE REVIEW

**Comment by prateekiiest** [comment]
same as #113

**Comment by rahulkumaran** [comment]
@prateekiiest I've been working on the Ceasarcipher since the beginning! And moreover this code is in Python! Could I know why the duplicate tag ?

**Comment by prateekiiest** [comment]
Its not that you cant add the same code.
It would be better if you could create a separate folder for both the languages :)

**Comment by rahulkumaran** [comment]
So under the crypto algos folder, do you want me to create a separate folder called "crypto algos in Python" or do you just want me to create a separate folder for the implementation of "Caesar Cipher in Python" ? :)

**Comment by prateekiiest** [comment]
just create `Python` and under that insert the code

**Review by soubh1k — COMMENTED** [review]
Just need a slight change. Instead of explicitly asking the user for an input, initialise a key and string within the program.

**Comment by rahulkumaran** [comment]
@prateekiiest @soubh1k made the necessary changes.
Please do have a look at it.
Created a separate _Python_ folder under the Cryptography folder and also initialised the key value and the strings to be encrypted and decrypted.

**Review by prateekiiest — CHANGES_REQUESTED** [review]
do like this
CaesarCipher/Python/Caesarcipher.py

**Comment by prateekiiest** [comment]
under RSA

**Comment by rahulkumaran** [comment]
The Caesarcipher should be under the crypto folder right? @prateekiiest

**Comment by prateekiiest** [comment]
yes under RSA folder

**Comment by rahulkumaran** [comment]
@prateekiiest added the code under /CaesarCipher/Python/Caesarcipher.py

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
