### PR TITLE
Implementation of bubble sort algorithm in python

### PR DESCRIPTION
**Pull request by rahuldcoder**

### CODE REVIEW

**Comment by rahuldcoder** [comment]
Can you provide me with reasons for the rejection of my request.

**Comment by soubh1k** [comment]
Check codeclimate. Put better variable names to ensure good readability.

**Comment by rahuldcoder** [comment]
I have changed variable names but whenever I try for a new pull request It shows me the old pull request.Help required.

**Review by rahuldcoder — COMMENTED** [review]
Please check my changes and give necessary feedback ASAP so that I can give more contributions

**Comment by rahuldcoder** [comment]
How do I reduce cognitive complexity

**Comment by shiveshchoudhary** [comment]
well cognitive complexity takes place when program encounter : (block suite) many times, i also tried many times but two three blocks just make it complexity to 6 or 7 hence only one liner functions are acceptable by code climate . so one thing u can do is to try to shift on c++ or c(i did this) as there are no blocks there and no specifications on intentation or try to break functions in 2 3 func so that max 2 block suites are encountered.

**Comment by rahuldcoder** [comment]
But only one-liner is not possible every time!!

**Review by rahuldcoder — COMMENTED** [review]
Plz check I have further tried to modularise the code

**Comment by shiveshchoudhary** [comment]
u say it right that one time is not possible everytime that is why i shift to c++ but it nearly impossible to pull request with python i tried a lot , only way to add such code is that u are head of respo and u add it otherwise the head accept it there might be a way too u can ask prateek sir if he is able to accept a pr with some of the test not passing(the best way learn c++ basics only take a week and do it in that .

**Comment by soubh1k** [comment]
I am closing this pull request. The current directory structure has been changed. Fork the new repo with the new directory structure. Insert the files in the new directory structure along with the appropriate readme's. Then create a new Pull Request.

Also check codeclimate and codacy issues.

**Pull request closed without merging**
