### PR TITLE
Create rsa.c

### PR DESCRIPTION
**Pull request by prateekiiest**
Adding solution for RSA algorithm

### CODE REVIEW

**Comment by prateekiiest** [comment]
I am adding solution for RSA algorithm

**Comment by smitbose** [comment]
Hi Prateek, sorry for getting to this request a bit late...why don't you comment the code, its just plain code, not good for someone who might be studying it...
Do it and generate the pull request back...I'll get to it

**Comment by prateekiiest** [comment]
ok

**Comment by smitbose** [comment]
Thanks prateek, I'm merging it.

**Pull request merged**
