### PR TITLE
Create BubbleSort.py

### PR DESCRIPTION
**Pull request by prateekiiest**

### CODE REVIEW

**Comment by prateekiiest** [comment]
Other sort solutions coming. 
If the sorts folder is created then I can add solution directly to the folder along with its README.md, then I can directly add solution for other sorts in that folder

**Comment by smitbose** [comment]
@prateekiiest well you see, python gives a really less clustered code, but the problem with it is that for someone who is looking at these codes, is highly unlikely to know python itself. A C or C++ implementation would be great as in IIEST, thats the first thing people are taught. And of-course someone in third or fourth year, likely knowing python, wont be looking for bubble sort or binary search implementations. Infact, in contests we mostly use STL for these purposes.

**Comment by prateekiiest** [comment]
Ok, I will implement the rest in C

**Comment by prateekiiest** [comment]
It will do good if a seperate readmes for each algorithm folders are created. There we can upload the videos, links
Specific resources for specific algos

**Comment by smitbose** [comment]
Look at the gh-pages branch on the repo @prateekiiest 
I have almost completed creating the basic template, for a blog , that will classify algos under some sections like Sorting, graphs, dp, etc. and there you can upload markdown or videos or pdfs whatever. I've almost completed the structure in my laptop, which I'll be pushing probably tomorrow, as I got a little busy with other stuff. You can clone that and enhance the site

**Comment by prateekiiest** [comment]
Sure

**Pull request closed without merging**
