### PR TITLE
Backtrack Problems

### PR DESCRIPTION
**Pull request by florist-notes**
1. nQueens
2. Sudoku

### CODE REVIEW

**Review by prateekiiest — APPROVED** [review]
Thanks !

**Comment by prateekiiest** [comment]
Can you show me the output please?

**Comment by florist-notes** [comment]
both outputs

**Comment by prateekiiest** [comment]
Its ok, but it would be better if under Backtracking you add a readme file where you upload the output along with some description of your code.

You can edit that in this readme only

**Comment by florist-notes** [comment]
OK, will do that.Will create a nice documentation.

**Comment by soubh1k** [comment]
This PR has been merged. Now write documentation.

**Pull request merged**
