### PR TITLE
Added a Bitwise operation program

### PR DESCRIPTION
**Pull request by mahak5**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
I guess its already included in the code repository

**Comment by shivhek25** [comment]
@prateekiiest No, that code is for checking whether a number is a power of 2. @mahek5 's code, on the other hand, prints the largest power of 2 <= the given number

**Comment by mahak5** [comment]
No, it isn't there @prateekiiest. What @shivhek25 mentioned is correct.

**Comment by prateekiiest** [comment]
Looks good 🎆 

Thanks for the contribution :1st_place_medal:

**Review by prateekiiest — APPROVED** [review]

**Comment by prateekiiest** [comment]
Add yourself in the contributors.md 😃

**Pull request merged**
