### PR TITLE
Added FFT and Commented code to Math Algos

### PR DESCRIPTION
**Pull request by abhisheknalla**
- [x] Fast Fourier Transformation

- [ ] Sum of squares of first N natural numbers

- [x] Checking for integer overflow on multiplication

- [ ] Convert Radian to Degree

- [x] K-th Primes

I have commented the codes and also added READMEs

### CODE REVIEW

**Comment by abhisheknalla** [comment]
Sir, should I be working on more math algorithms? .

**Comment by abhisheknalla** [comment]
Sir, can i get a feedback ?

**Review by prateekiiest — APPROVED** [review]

**Comment by prateekiiest** [comment]
I think its good.
What do you say @soubh1k ?

**Comment by prateekiiest** [comment]
I am merging this

**Pull request merged**
