### PR TITLE
Pointer based linklist in c++.

### PR DESCRIPTION
**Pull request by sgrG24**
This program contains functions for performing basic operation.

### CODE REVIEW

**Review by prateekiiest — CHANGES_REQUESTED** [review]
If you could comment out within all the code apart from the functionality of each function it will be much easier to understand

**Comment by sgrG24** [comment]
Okay sir, i will comment in each part so that it is easier for others to understand. Sir, any other corrections?

**Comment by prateekiiest** [comment]
its good , but some issues needs to be fixed for Codacy

**Comment by sgrG24** [comment]
Ok i will update this code by evening.

**Comment by sgrG24** [comment]
Sir i add comments in each section, please take a look in it and if there is any correction, so tell me.

**Comment by prateekiiest** [comment]
@sgrG24 there are only two issues as you can see here in codacy.
https://www.codacy.com/app/prateekkol21/Algorithms/pullRequest?prid=1123236

**Review by prateekiiest — APPROVED** [review]

**Comment by sgrG24** [comment]
ok, i will solve this.

**Comment by sgrG24** [comment]
Sir  i made some changes.

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
