### PR TITLE
Java program for 0-1 knapsack

### PR DESCRIPTION
**Pull request by ManognaMutyala**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

#191 

## SHORT DESCRIPTION

Java program for knapsack algorithm

### CODE REVIEW

**Review by prateekiiest — CHANGES_REQUESTED** [review]
how can i differentiate from the already existing code.

please show me the difference between the two by some output or time complexities if any

**Comment by ManognaMutyala** [comment]
Sir, I went through the other program after you asked me for the difference.The other program they have written is not a greedy approach.They have written the dynamic approach but they have placed it under greedy approach.Greedy approach is different from what they have mentioned.I would also like to write greedy approach program too.Kindly let me the solution for the above @prateekiiest

**Comment by prateekiiest** [comment]
it will be good if you can compare between the two codes in times of time complexity

**Comment by ManognaMutyala** [comment]
Complexity in greedy programming would be O(nlogn) whereas in dynamic programming it would be 
O(nW).So Sir do you want me to specify it over there in the description?

**Comment by prateekiiest** [comment]
can you add a plot in the readme showing the time complexity differences

**Review by prateekiiest — APPROVED** [review]

**Comment by prateekiiest** [comment]
Looks good 🎆 

Thanks for the contribution :1st_place_medal:

**Pull request merged**
