### PR TITLE
C program for Car Animation

### PR DESCRIPTION
**Pull request by rahulkumaran**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

with reference to the gitter convo

## SHORT DESCRIPTION

the car is drawn using the line function and animation takes place

## TESTING

you can compile and run it

### CODE REVIEW

**Comment by rahulkumaran** [comment]
The output of the program is shown below
screenshot from 2017-12-16 15-52-31
screenshot from 2017-12-16 15-52-35
screenshot from 2017-12-16 15-52-37
screenshot from 2017-12-16 15-52-40

**Review by prateekiiest — APPROVED** [review]

**Review by prateekiiest — APPROVED** [review]
Pretty Good !!

**Comment by prateekiiest** [comment]
Looks good 🎆 

Thanks for the contribution :1st_place_medal:

**Comment by rahulkumaran** [comment]
Thanks for merging it 😃

**Pull request merged**
