### PR TITLE
The Knapsack problem.

### PR DESCRIPTION
**Pull request by heisenberg-2505**
This is a C++ code that solves the 0-1 knapsack problem.

### CODE REVIEW

**Comment by manojsrivatsavsfu** [comment]
Which variant of the knapsack problem ?
There are many example 0-1 kanpsack etc

**Comment by heisenberg-2505** [comment]
This is a 0-1 knapsack problem.

**Review by prateekiiest — CHANGES_REQUESTED** [review]
Include the name 0-1 Knapsack  Problem in the comments above

**Comment by heisenberg-2505** [comment]
Done.

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
