### PR TITLE
Added Boyer-Moore string search algorithms

### PR DESCRIPTION
**Pull request by dhruvapte26**

### CODE REVIEW

**Review by prateekiiest — COMMENTED** [review]
What's the speciality of this search algo?
It would be better if you could compare this with the existing ones

**Comment by dhruvapte26** [comment]
It is a standard string search algorithm which runs faster as the pattern length increases and is best for multiple-searches. You can check out more on this at [Wikipedia](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm)

**Comment by prateekiiest** [comment]
@the-ethan-hunt , I really appreciate that. It would be great if you could add some graphs or plots along with this code in the same branch , comparing this search algo with existing linear and binary search ones.
It would be neat and complete then 💯

**Comment by dhruvapte26** [comment]
Sure, @prateekiiest !

**Comment by prateekiiest** [comment]
You dont need to close this. You can add a new file in this branch only

**Comment by prateekiiest** [comment]
click on the commit, head to right, you will find a pen icon. click on it to edit.

Head over to  the folder edit section in the top. Go to string_search folder. Create a slash and name the folder visualization and add the graph. Commit

**Comment by dhruvapte26** [comment]
Add the time complexity graph :sweat_smile:

**Comment by prateekiiest** [comment]
What I get from the graph, this algorithm is not as good as the linear and binary.

**Comment by dhruvapte26** [comment]
I have made the worst case scenario here. :sweat_smile: . Plus, here we can understand that binary search is the best in such cases

**Comment by prateekiiest** [comment]
Analysis works better if you can work with the average cases, I believe

**Comment by dhruvapte26** [comment]
The average case analysis for time complexity of Boyer Moore algorithms is quite complex @prateekiiest . The system is random as I read in the conclusions of [this paper](https://pdfs.semanticscholar.org/64ce/dd0102c30de9b9125560955b9474bc76684e.pdf). Please correct me if I am wrong

**Comment by prateekiiest** [comment]
check if in average case, the above algo turns out to be better

**Comment by prateekiiest** [comment]
yeah that's complex though.
Ok I am merging this.

Thanks for the contribution @the-ethan-hunt

**Pull request merged**
