### PR TITLE
Added Linked List operations based on Arrays and created new separate folders for both Linked Lists based on Arrays and Pointers

### PR DESCRIPTION
**Pull request by Zanark**
## ISSUE NUMBER

[Issue #133 ](https://github.com/codeIIEST/Algorithms/issues/133) 

## SHORT DESCRIPTION

I added a C++ file containing algorithms on Linked List operations based on Arrays along with a README.md. I created two new folders for **Array based LLs** and **Pointer based LLs**. I will add more algorithms to the files when I find more. This had to be submitted because **my current no. of commits are 0** 😢 😭 

## TESTING

The C++ file can be run using any compiler that can run a C++ file.
The README.md files is displayed below the list of files on opening the folder

### CODE REVIEW

**Comment by prateekiiest** [comment]
did you fork the repo again ?

**Comment by prateekiiest** [comment]
I can't understand why its showing 0 commits

**Comment by Zanark** [comment]
yes i had to because it wasn't allowing me to send a pull request

**Comment by Zanark** [comment]
Should have I not forked the repo again?
I forked it because I saw the active members doing the same

**Comment by prateekiiest** [comment]
update yourself with your previous PRs in the contributors.md file and mail the KWOC members about this.

**Comment by Zanark** [comment]
Sir, are you asking me to mail the KWoC members regarding the issue of the commit history  getting  erased which led to our contributions being reset to 0?

**Comment by prateekiiest** [comment]
yes @Zanark

**Comment by Zanark** [comment]
Sir I resolved the errors but I am having some conflicts because of updating the contributions file on a branch of mine due to which some discrepancies have arised 
I'll be sending you a new PR soon
I hope you don't mind

**Pull request closed without merging**
