### PR TITLE
Project Euler

### PR DESCRIPTION
**Pull request by rahulkumaran**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER
#128 

## SHORT DESCRIPTION

added problem 20 of project euler in a new folder under competitive programming

## TESTING

just run the code and it'll automatically display the answer

### CODE REVIEW

**Comment by rahulkumaran** [comment]
@prateekiiest please have a look at this! made some changes in the directory actually so closed my PR #152 .. just added a project euler directory under the competitive programming section!
Please approve the same as I can add more codes then

**Comment by rahulkumaran** [comment]
@prateekiiest , I have a small doubt! I guess all the PR's have been closed! Any reason for that? Also, do we submit new PRs for the same again?

**Comment by prateekiiest** [comment]
kindly see the discussion in the gitter channel.

It all occurred automatically due to some untracked commits

**Comment by rahulkumaran** [comment]
Oh okay! My gitter has not been functioning properly since yesterday! It's just closing automatically immediately after I open the app! So couldn't check the gitter channel

**Pull request closed without merging**
