### PR TITLE
 Create Print_Binary_Tree_in_Vetical_Order using Hash Tables

### PR DESCRIPTION
**Pull request by AdilMah**

### CODE REVIEW

**Comment by soubh1k** [comment]
Just an advice, don't commit after every atomic work (creating/deleting/updating a file). Make a commit only after you have made substantial changes.

**Comment by AdilMah** [comment]
Thanks for the advice.:)

**Comment by prateekiiest** [comment]
squash the commits @AdilMah

**Comment by prateekiiest** [comment]
I am closing this as this PR construct is not good.
Please follow the above rules and create a new PR

**Comment by AdilMah** [comment]
How can I improve the PR Construct??

**Comment by AdilMah** [comment]
and if i send a pull request now will not include the previous commits???pls help

**Pull request closed without merging**
