### PR TITLE
Cocktail Shaker Sort in Python

### PR DESCRIPTION
**Pull request by Subhajit135**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION
Implementation of Cocktail Shaker Sort in Python.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
what is the utility / functionality of this code?

**Comment by Subhajit135** [comment]
It's a sorting algorithm to sort out a list in ascending order.

**Comment by prateekiiest** [comment]
we have too many sorting algos.
What sets this out?

**Comment by Subhajit135** [comment]
It's one of the rare sorting algorithms out there though it's not that efficient .

**Pull request closed without merging**
